server:
  port: 8080

database:
  host: localhost
  port: 5432
  name: ecomdb
  user: ecomuser
  password: ecompassword
  sslmode: disable

redis:
  host: localhost
  port: 6379

rabbitmq:
  host: localhost
  port: 5672