root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/worker.exe ./cmd/worker"
bin = "tmp/worker.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "docker", "docs", "infra", "scripts"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
follow_symlink = true
delay = 1000 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true