apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: ${NAMESPACE}
data:
  APP_SERVER_PORT: "8080"
  APP_DATABASE_HOST: "postgres"
  APP_DATABASE_PORT: "5432"
  APP_DATABASE_NAME: "${DB_NAME}"
  APP_DATABASE_SSLMODE: "disable"
  APP_REDIS_HOST: "redis"
  APP_REDIS_PORT: "6379"
  APP_RABBITMQ_HOST: "rabbitmq"
  APP_RABBITMQ_PORT: "5672"